# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'capybara'
require 'capybara/rspec'
# require 'capybara/poltergeist'
require 'capybara/dsl'
require 'rspec/core/rake_task'
require 'selenium-webdriver'
# require 'byebug'

# in spec/support/ and its subdirectories.
require 'support/login_methods'

RSpec.configure do |config|
  config.include Capybara::DSL, type: :request
  Capybara.default_driver = :selenium_firefox

  Capybara.register_driver :selenium_firefox do |app|
    Capybara::Selenium::Driver.new(app, browser: :firefox, marionette: true)
  end

end

